name: Build OpenCV for Windows x64

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout OpenCV
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout OpenCV Contrib
        run: |
          git clone https://github.com/opencv/opencv_contrib.git opencv_contrib

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure OpenCV
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -DBUILD_opencv_world=ON \
            -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
            -DWITH_CUDA=OFF \
            -DWITH_MSMF=ON \
            -DWITH_IPP=ON \
            -DWITH_OPENCL=ON \
            -DWITH_MSMF_DXVA=ON \
            -DCMAKE_INSTALL_PREFIX=install ..

      - name: Build OpenCV
        shell: bash
        run: |
          cd build
          cmake --build . --config Release --target INSTALL

      - name: Zip artifacts
        shell: bash
        run: |
          cd build
          powershell Compre
